# SPDX-License-Identifier: GPL-2.0-only OR MIT
#
# Makefile for DockChannel HID transport drivers
#

obj-$(CONFIG_HID_DOCKCHANNEL)	+= dockchannel-hid.o
obj-$(CONFIG_HID_DOCKCHANNEL_KUNIT_TEST) += dockchannel-hid-protocol-test.o
